version: '3.2'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    container_name: testDocker
    image: store/intersystems/iris-community:2019.4.0.383.0
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - ./backend:/app

  
